### PR TITLE
Fix pages layout

### PR DESCRIPTION
**Pull request by StarNumber12046**

### CODE REVIEW

**Comment by XPower7125** [comment]
will add

**Comment by StarNumber12046** [comment]
you need to fix a conflit

**Comment by XPower7125** [comment]
committing

**Comment by StarNumber12046** [comment]
no wait

**Comment by XPower7125** [comment]
conflicting files

**Comment by StarNumber12046** [comment]
ye, try using VSC or GH desktop

**Comment by XPower7125** [comment]
maybe

**Pull request merged**
